---
- name: Install and Configure promtail
  hosts: all
  become: yes
  roles:
    - role: promtail
      vars:
        server:
          http_listen_port: 9080
          grpc_listen_port: 9095
        clients:
          url: "http://lokiuser:lokip@ssword!@192.168.0.133:80/loki/api/v1/push"
          external_labels:
            host: "{{ ansible_hostname }}"
        positions:
          filename: "/var/log/positions.yaml"
        scrape_configs:
          - job_name: journal
            journal:
              json: false
              max_age: 12h
              path: /var/log/journal
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels: ["__journal__systemd_unit"]
                target_label: "unit"
          - job_name: ec2-logs
            ec2_sd_configs:
              - region: us-east-2
                access_key: REDACTED
                secret_key: REDACTED
            relabel_configs:
              - source_labels: [__meta_ec2_tag_Name]
                target_label: name
                action: replace
              - source_labels: [__meta_ec2_instance_id]
                target_label: instance
                action: replace
              - source_labels: [__meta_ec2_availability_zone]
                target_label: zone
                action: replace
              - action: replace
                replacement: /var/log/**.log
                target_label: __path__
              - source_labels: [__meta_ec2_private_dns_name]
                regex: "(.*)"
                target_label: __host__
