---
- name: Install and Configure promtail
  hosts: all
  become: yes
  roles:
    - role: promtail
      vars:
        # loki_url format: {{ protocol }}//{{ loki_username }}:{{ loki_password }}@{{ loki_host }}:{{ loki_port }}
        # e.g. http://lokiuser:lokip@ssword!@192.168.0.133:80
        loki_url: http://lokiuser:lokip@ssword!@192.168.0.133:80
